[book]
authors = ["Willem Olding"]
language = "en"
multilingual = false
src = "src"
title = "Zipline Specification"

[output.html]
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.katex]
after = ["links"]
