name: Preprocessor tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests-main:
    name: Tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node: [20]
    steps:
      # <common-build> - Uses YAML anchors in the future
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
      - name: Node.js version
        id: node
        run: echo "v8CppApiVersion=$(node --print "process.versions.modules")" >> $GITHUB_OUTPUT
      - name: Restore dependencies
        uses: actions/cache@master
        id: cache-deps
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-${{ steps.node.outputs.v8CppApiVersion }}-${{ hashFiles('**/yarn.lock', '**/package.json') }}
      - name: Install & build
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile && yarn build
        working-directory: preprocessor
      - name: Build
        if: steps.cache-deps.outputs.cache-hit == 'true'
        run: yarn build
        working-directory: preprocessor
      # </common-build>

      - name: Lint
        run: yarn lint
        working-directory: preprocessor
      - name: Check Types
        run: yarn check-types
        working-directory: preprocessor
